drop table CUSTOMERS;

create table CUSTOMERS (
  ID BIGINT NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR(255),
  LAST_NAME  VARCHAR(255)
);
INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME) VALUES (0, 'Dan', 'Funk');
INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Bethany', 'Teachman');
INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME) VALUES (0, 'Sam', 'Portnow');